// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB85RJ2fg9TZq_3tpOj491gsbVeXsk50Zk',
    appId: '1:702473225635:web:9565336ecb4c1777a78616',
    messagingSenderId: '702473225635',
    projectId: 'todo-app-2fb32',
    authDomain: 'todo-app-2fb32.firebaseapp.com',
    storageBucket: 'todo-app-2fb32.appspot.com',
    measurementId: 'G-R0D685GQX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtjBhHh1EbEvPNE8pRMBi4Z1g_VZvNKMY',
    appId: '1:702473225635:android:ae39f7f1dc42023fa78616',
    messagingSenderId: '702473225635',
    projectId: 'todo-app-2fb32',
    storageBucket: 'todo-app-2fb32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh3jfLV0QviREFwu512Jnk3A-irKUQdE8',
    appId: '1:702473225635:ios:9956653d2c40b524a78616',
    messagingSenderId: '702473225635',
    projectId: 'todo-app-2fb32',
    storageBucket: 'todo-app-2fb32.appspot.com',
    iosBundleId: 'com.example.todoCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh3jfLV0QviREFwu512Jnk3A-irKUQdE8',
    appId: '1:702473225635:ios:9956653d2c40b524a78616',
    messagingSenderId: '702473225635',
    projectId: 'todo-app-2fb32',
    storageBucket: 'todo-app-2fb32.appspot.com',
    iosBundleId: 'com.example.todoCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB85RJ2fg9TZq_3tpOj491gsbVeXsk50Zk',
    appId: '1:702473225635:web:0e30771d381126b1a78616',
    messagingSenderId: '702473225635',
    projectId: 'todo-app-2fb32',
    authDomain: 'todo-app-2fb32.firebaseapp.com',
    storageBucket: 'todo-app-2fb32.appspot.com',
    measurementId: 'G-0BN9SWJMFH',
  );
}
